config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "pages#home"

  get "/movies/random", to: "movies#random", as: :random_movie
  get "/movies", to: "movies#index"
  resources :movies, only: [:show] do
    resources :favorites, only: [:new, :create]
  end


  get "/lists", to: "lists#index"
  get "/lists/new", to: "lists#new", as: :new_list
  get "lists/:id", to: "lists#show", as: :list
  post "/lists", to: "lists#create"
  get "/lists/:id/edit", to: "lists#edit", as: :edit_list
  patch "/lists/:id", to: "lists#update"
  delete "/lists/:id", to: "lists#destroy", as: :destroy_list

  delete "/favorites/:id", to: "favorites#destroy", as: :destroy_fav
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, presence: true
  validates :list, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :movies, through: :favorites

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :favorites, dependent: :destroy

  include PgSearch::Model
  pg_search_scope :search_by_title_and_director,
  against: [ :title, :director ],
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists

  validates :name, presence: true
  validates :surname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :surname])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :surname])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = Favorite.all
  end

  def new
    @favorite = Favorite.new
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @favorite = Favorite.new(favorite_params)
    @favorite.movie = @movie
    @list = @favorite.list
    if @favorite.save
      redirect_to movie_path(@movie), notice: "This movie was added to the list !"
    else
      render "/movies/show", status: :unprocessable_entity
    end
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy
    redirect_to list_path(@favorite.list), status: :see_other
  end

  private

  def favorite_params
    params.require(:favorite).permit(:list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @user = current_user
    @list = List.create(list_params)
    @list.user = @user
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    redirect_to list_path(@list)
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    if params[:query].present?
      @movies = Movie.search_by_title_and_director(params[:query])
    else
      @movies = Movie.all
    end
  end

  def show
    @movie = Movie.find(params[:id])
    @favorite = Favorite.new
    @lists = List.all
  end

  def random
    @movies = Movie.all
    @movie = @movies[rand(@movies.length)]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :surname])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhatMovie</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<div class="container">
  <h3>Edit my list's name</h3>

  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/index.html.erb
<div class="container">
  <% current_user.lists.each do |list| %>
    <ul>
      <li><%= link_to list.name, list_path(list) %></li>
    </ul>
  <% end %>

  <%= link_to "Home", root_path %>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h3>Create a new list</h3>

  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.submit %>
  <% end %>

  <%= link_to "Back to my lists", lists_path %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <h3>
  <%= @list.name %>
  </h3>

  <% @list.favorites.each do |favorite| %>
    <%= favorite.movie.title %>
    <%= link_to "Delete", destroy_fav_path(favorite), data: {turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
  <% end %>


  <%= link_to "Edit my list's name", edit_list_path(@list) %>
  <%= link_to "Back to my lists", lists_path %>
</div>

app/views/movies/index.html.erb
<div class="container">
  <div class="d-flex justify-content-between mt-3 mb-3">
    <h3 class="mb-0">🎬 Find a movie </h3>
    <div class="card-lg">
      <%= link_to "No idea ? Let's pick randomly !", random_movie_path %>
    </div>
  </div>

  <div class="form-search">
    <%= form_with url: movies_path, method: :get, class: "d-flex" do |f| %>
      <%= f.text_field :query,
        class: "form-control form-search input",
        placeholder: "Batman, Nolan, Titanic...",
        value: params[:query] %>
      <%= button_tag(type: "submit", class: "btn btn-dark form-search button") do %>
        <i class="fa-solid fa-magnifying-glass"></i>
      <% end %>
    <% end %>
  </div>

  <div class="d-flex flex-wrap justify-content-between">
    <% if @movies.present? %>
      <% @movies.each do |movie| %>
        <div class="card mt-3" style="width: 18rem">
          <img class="card-img-top" src="<%= movie.poster_url %>" alt="Card image cap">
          <div class="card-body">
            <h4><%= link_to movie.title, movie_path(movie) %></h4>
            <ul class="card-text">
              <li>Category : <%= movie.category %></li>
              <li>Year : <%= movie.year %></li>
              <li>Rating : <%= movie.rating %></li>
            </ul>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>Sorry, not results !</p>
    <% end %>
  </div>

app/views/movies/random.html.erb
<div class="container">
  <h3>🎬 We picked... </h3>

  <%= link_to @movie.title, movie_path(@movie) %>
  <%= @movie.description %>
  <img src="<%= @movie.poster_url %>" alt="img">
  <%= @movie.year %>

  <div class="d-flex justify-content-between">
    <div><%= link_to movie_path(@movie) do %>
      <button class="btn btn-dark"><i class="fa-solid fa-plus"></i> Tell me more about it</button>
      <% end %>
    </div>
    <div><%= link_to random_movie_path do %>
      <button class="btn btn-outline-dark"><i class="fa-solid fa-rotate-right"></i> Another pick please</button>
      <% end %>
    </div>
  </div>
</div>

app/views/movies/show.html.erb
<div class="container">
  <h3><%= @movie.title %></h3>
  <img src="<%= @movie.poster_url %>" alt="img">
  <%= @movie.category %>
  <%= @movie.description %>
  <%= @movie.year %>
  <%= @movie.rating %>

  <%= simple_form_for [@movie, @favorite] do|f|%>
    <%= f.association :list %>
    <%= f.submit "add this movie to my list"%>
  <%end%>

  <%= link_to "Back to movies", movies_path %>
  <%= link_to "Home", root_path %>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url('<%= asset_path "hp_banner.jpg" %>')">
  <div class="container">
    <h1><strong>What movie tonight ?</strong></h1>
    <p>Let's try not to spend more time finding the movie idea than watching the movie</p>
    <%= link_to movies_path do %>
      <button class= "btn-flat">See the movies</button>
    <% end %>
  </div>
</div>


<div class="container">
  <%= link_to "Create a list", new_list_path %>
</div>

app/views/pages/test.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url('<%= asset_path "hp_banner.jpg" %>')">
  <div class="container">
    <h1><strong>What movie tonight ?</strong></h1>
    <p>Let's try not to spend more time finding the movie idea than watching the movie</p>
    <%= link_to movies_path do %>
      <button class= "btn-flat">See the movies</button>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "movie.png" %>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to movies_path do %>
              <button class= "btn btn-outline-dark me-3">All movies</button>
            <% end %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "avatar.png", class: "avatar", alt: "dropdown menu" %>
          </a>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "My lists", lists_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>